# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title.xci
# IP: The module: 'blk_mem_title' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_title'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title.xci
# IP: The module: 'blk_mem_title' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_title'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
