# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.cache/wt [current_project]
set_property parent.project_path D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/Desktop/all in 1.coe}}
add_files c:/Users/lyk02/Desktop/2026Proj/end/firework_all.coe
add_files c:/Users/lyk02/Desktop/testpic1.coe
add_files c:/Users/lyk02/Desktop/testpic2.coe
add_files c:/Users/lyk02/Desktop/testpic3.coe
add_files c:/Users/lyk02/Desktop/testtrack1.coe
add_files c:/Users/lyk02/Desktop/testtrack2.coe
add_files c:/Users/lyk02/Desktop/testtrack3.coe
add_files c:/Users/lyk02/Desktop/test.coe
add_files c:/Users/lyk02/Desktop/gameover.coe
read_verilog -library xil_defaultlib {
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/16_bar_volume_depiction.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/Car.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Continuous_full_bar.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Finishing_Line.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/FloatBar.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Mode_multi_bar.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Normal_Tree.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Number_1.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Number_2.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Number_3.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Pine_tree.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Racing_Boy.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Random.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Ready_state.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Road_marking.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Self_driving.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/TaskB.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/UpDownBarIndividual.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/VolumeBar.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Word_Ready.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Word_Start.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/clock_dff_spc.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/continuous_volume_depiction.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/frequency_generator.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/peak_volume.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/rom_car.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/rom_oppcar.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/segment_999.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/straight_road.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/imports/new/volume_7_seg.v
  D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v
}
read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosetrack2/blk_mem_choosetrack2.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosetrack2/blk_mem_choosetrack2_ooc.xdc]

read_ip -quiet D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_title/blk_mem_title_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_firework/blk_mem_firework.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_firework/blk_mem_firework_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar1/blk_mem_choosecar1.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar1/blk_mem_choosecar1_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar2/blk_mem_choosecar2.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar2/blk_mem_choosecar2_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar3/blk_mem_choosecar3.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosecar3/blk_mem_choosecar3_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosetrack1/blk_mem_choosetrack1.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_choosetrack1/blk_mem_choosetrack1_ooc.xdc]

read_ip -quiet d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_gameover/blk_mem_gameover.xci
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/sources_1/ip/blk_mem_gameover/blk_mem_gameover_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Vivado/Project/Final/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
